// src/data.js
export const animals = [
    { name: "Alligator", soundUrl: "AnimalSounds/Alligator.mp3" },
    { name: "Bär", soundUrl: "AnimalSounds/Bär.mp3" },
    { name: "Buckelwal", soundUrl: "AnimalSounds/Buckelwal.mp3" },
    { name: "Elch", soundUrl: "AnimalSounds/Elch.mp3" },
    { name: "Elefant", soundUrl: "AnimalSounds/Elefant.mp3" },
    { name: "Elster", soundUrl: "AnimalSounds/Elster.mp3" },
    { name: "Esel", soundUrl: "AnimalSounds/Esel.mp3" },
    { name: "Europäischer Falke", soundUrl: "AnimalSounds/Europäischer Falke.mp3" },
    { name: "Fledermaus", soundUrl: "AnimalSounds/Fledermaus.mp3" },
    { name: "Frosch", soundUrl: "AnimalSounds/Frosch.mp3" },
    { name: "Gans", soundUrl: "AnimalSounds/Gans.mp3" },
    { name: "Gecko", soundUrl: "AnimalSounds/Gecko.mp3" },
    { name: "Giraffe", soundUrl: "AnimalSounds/Giraffe.mp3" },
    { name: "Großer Dachs", soundUrl: "AnimalSounds/Großer Dachs.mp3" },
    { name: "Brachvogel", soundUrl: "AnimalSounds/Brachvogel.mp3" },
    { name: "Hahn", soundUrl: "AnimalSounds/Hahn.mp3" },
    { name: "Heuschrecke", soundUrl: "AnimalSounds/Heuschrecke.mp3" },
    { name: "Hummel", soundUrl: "AnimalSounds/Hummel.mp3" },
    { name: "Hyäne", soundUrl: "AnimalSounds/Hyäne.mp3" },
    { name: "Jägerliste", soundUrl: "AnimalSounds/Jägerliste.mp3" },
    { name: "Katze", soundUrl: "AnimalSounds/Katze.mp3" },
    { name: "Klapperschlange", soundUrl: "AnimalSounds/Klapperschlange.mp3" },
    { name: "Kranich", soundUrl: "AnimalSounds/Kranich.mp3" },
    { name: "Löwe", soundUrl: "AnimalSounds/Löwe.mp3" },
    { name: "Mantelbrüllaffe", soundUrl: "AnimalSounds/Mantelbrüllaffe.mp3" },
    { name: "Papagei", soundUrl: "AnimalSounds/Papagei.mp3" },
    { name: "Pferd", soundUrl: "AnimalSounds/Pferd.mp3" },
    { name: "Reh", soundUrl: "AnimalSounds/Reh.mp3" },
    { name: "Schaf", soundUrl: "AnimalSounds/Schaf.mp3" },
    { name: "Schlammrutschkuh", soundUrl: "AnimalSounds/Schlammrutschkuh.mp3" },
    { name: "Schwan", soundUrl: "AnimalSounds/Schwan.mp3" },
    { name: "Schwarzer Rabe", soundUrl: "AnimalSounds/Schwarzer Rabe.mp3" },
    { name: "Schwein", soundUrl: "AnimalSounds/Schwein.mp3" },
    { name: "Stieglitz", soundUrl: "AnimalSounds/Stieglitz.mp3" },
    { name: "Taube", soundUrl: "AnimalSounds/Taube.mp3" },
    { name: "Tiger", soundUrl: "AnimalSounds/Tiger.mp3" },
    { name: "Truthan", soundUrl: "AnimalSounds/Truthan.mp3" },
    { name: "Uhu", soundUrl: "AnimalSounds/Uhu.mp3" },
    { name: "Weißkopfseeadler", soundUrl: "AnimalSounds/Weißkopfseeadler.mp3" },
    { name: "Wolf", soundUrl: "AnimalSounds/Wolf.mp3" },
    { name: "Ziege", soundUrl: "AnimalSounds/Ziege.mp3" },
    { name: "Zikadenchor", soundUrl: "AnimalSounds/Zikadenchor.mp3" },
  ];